### ISSUE TITLE
Get an Error

### ISSUE THREAD

**Issue by WongIong** [TonimatasMCDEV/PerWorldPlugins-Reworked#1]
https://pastebin.com/0HqqJzvG
I have been noticed that which is not a PWP problem.
Personally think it is not necessary to make them work with.
So I wanna know that if there is a way to block this error msg? (maybe a setting in config?)

**Comment by TonimatasMCDEV** [comment]
> https://pastebin.com/0HqqJzvG I have been noticed that which is not a PWP problem. Personally think it is not necessary to make them work with. So I wanna know that if there is a way to block this error msg? (maybe a setting in config?)

But is everything working correctly for you?
